name: Alex's Shenanigans
description: The daily shenanigans of a developer
url: https://alexwang.ca
title: Alex's Adventures
author: Alex Wang
markdown: kramdown
timezone: America/New_York
permalink: pretty